[package]
name = "libpledge"
version = "0.1.0"
edition = "2021"

[workspace]
members = [
    "bpfvm"
]

[dependencies]
lazy_static = "1.4.0"
libc = { version = "0.2.132", features = ["extra_traits"] }
bpfvm = { version = "0.1.0", path = "bpfvm" }
thiserror = "1.0.35"

[dev-dependencies]
nix = "0.25.0"
log = "0.4.17"
test-log = "0.2.11"
env_logger = "0.9.1"
