[package]
name = "bpfvm"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libc = { version = "0.2.133", features = ["extra_traits"] }
log = "0.4.17"
thiserror = "1.0.35"

[dev-dependencies]
env_logger = "0.9.1"
test-log = "0.2.11"
